baseurl: /lego-songbook
description: Dwell in the house of the Lord.
highlighter: rouge
plugins:
- jekyll-feed
title: Lego Songbook
url: https://kipyin.github.io/
version: 2019.12.3
sheet_link: http://q4vafl4ua.bkt.clouddn.com/
